name: MyMaid
main: xyz.jaoafa.mymaid.MyMaid
version: 0.0.1
description: General Plugin
database: true
author: mine_book000
website: https://jaoafa.xyz/
default-permission: NOT_OP
commands:
   jf:
      description: Say jaoafa
      usage: /<command>
      permission: mymaid.jf
      permission-message: You do not have permission to perform this command.
   dt:
      description: Teleport to dynmap location.
      usage: /<command> [player] <location>
      permission: command_teleport.dt
      permission-message: You do not have permission to perform this command.
   g:
      description: Change your gamemode
      usage: /<command> <0|1|2|3>
      permission: mymaid.gamemode
      permission-message: You do not have permission to perform this command.
   chat:
      description: Make chat with fake player
      usage: /<command> <fake player> <message>
      permission: mymaid.chat
      permission-message: You do not have permission to perform this command.
   iphost:
      description: Find out host name from ip address
      usage: /<command>
      permission: mymaid.iphost
      permission-message: You do not have permission to perform this command.
   data:
      description: Show Server data
      usage: /<command>
      permission: mymaid.data
      permission-message: You do not have permission to perform this command.
   tnt:
      description: TNT Explode is what(philosophical)
      usage: /<command>
      permission: mymaid.tnt
      permission-message: You do not have permission to perform this command.
   afk:
      description: AFK is not AFK
      usage: /<command>
      permission: mymaid.afk
      permission-message: You do not have permission to perform this command.
   j2:
      description: Say jaojao
      usage: /<command>
      permission: mymaid.j2
      permission-message: You do not have permission to perform this command.
   vote:
      description: Console only
      usage: /<command>
      permission: mymaid.vote
      permission-message: You do not have permission to perform this command.
   sign:
      description: Change sentence of sign
      usage: /<command> set <row number> <new message>
      permission: mymaid.sign
      permission-message: You do not have permission to perform this command.
   signlock:
      description: Lock the sign
      usage: /<command>
      permission: mymaid.signlock
      permission-message: You do not have permission to perform this command.
   save-world:
      description: Save the world
      usage: /<command>
      permission: pin_code_auth.save-world
      permission-message: You do not have permission to perform this command.
   head:
      description: Give player skull to you
      usage: /<command> <player>
      permission: mymaid.head
      permission-message: You do not have permission to perform this command.
   cmdb:
      description: Give command block to you
      usage: /<command>
      permission: mymaid.cmdb
      permission-message: You do not have permission to perform this command.
   book:
      description: Create command makes book
      usage: /<command>
      permission: mymaid.book
      permission-message: You do not have permission to perform this command.
   jail:
      description: Put into eden of south
      usage: |-
             
             /<command> add <player> - Put player into jail
             /<command> remove <player> - Release player from jail
             /<command> list - Show jailer list
      permission: mymaid.jail
      permission-message: You do not have permission to perform this command.
   access:
      description: User Access Data
      usage: /<command> <player>
      permission: mymaid.access
      permission-message: You do not have permission to perform this command.
   ja:
      description: Say jaiuwa
      usage: /<command>
      permission: mymaid.ja
      permission-message: You do not have permission to perform this command.
   cmdsearch:
      description: cmdblock search
      usage: /<command>
      permission: mymaid.cmdsearch
      permission-message: You do not have permission to perform this command.
   skk:
      description: SiKaKu reload
      usage: /<command>
      permission: mymaid.skk
      permission-message: You do not have permission to perform this command.