name: MyMaid
main: xyz.jaoafa.mymaid.MyMaid
version: 0.0.1
description: General Plugin
database: true
author: mine_book000
website: https://jaoafa.xyz/
default-permission: NOT_OP
commands:
   jf:
      description: jaoafa
      usage: /<command>
      permission: mymaid.jf
      permission-message: You dont have <permission>
   dt:
      description: Town, City, Country Teleport Command.
      usage: /<command> [name]
      permission: command_teleport.dt
      permission-message: You do not have permission to perform this command.
   g:
      description: gamemode changed.
      usage: /<command>
      permission: mymaid.gamemode
      permission-message: You do not have permission to perform this command.
   chat:
      description: chat gisou
      usage: /<command> [Player] [Message]
      permission: mymaid.chat
      permission-message: You do not have permission to perform this command.
   iphost:
      description: ip to host name.
      usage: /<command>
      permission: mymaid.iphost
      permission-message: You do not have permission to perform this command.
   data:
      description: Server data
      usage: /<command>
      permission: mymaid.data
      permission-message: You do not have permission to perform this command.
   tnt:
      description: TNT Explode
      usage: /<command>
      permission: mymaid.tnt
      permission-message: You do not have permission to perform this command.
   afk:
      description: AFK
      usage: /<command>
      permission: mymaid.afk
      permission-message: You do not have permission to perform this command.